[package]
name = "MujicaLang"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
lalrpop-util = { version = "0.22.1", features = ["lexer"] }
clap = { version = "4", features = ["derive"] }
